image: k8s-master.kzml.com.cn:5443/workspace-full:latest
tasks:
  - init: |
      go get github.com/spf13/cobra/cobra
      go build
    command: |
      ./mycli --help
vscode:
  extensions:
    - golang.go
